shared:
    image: node:8

jobs:
    main:
        environment:
            SD_SONAR_OPTS: ""
        requires: [~pr, ~commit]
        steps:
            - install: npm install
            - test: npm test
