shared:
    image: node:8

jobs:
    main:
        environment:
            SD_SONAR_OPTS: "-Dsonar.sources=index.js -Dsonar.javascript.lcov.reportPath=${SD_ARTIFACTS_DIR}/coverage/lcov.info"
        requires: [~pr, ~commit]
        steps:
            - install: npm install
            - test: npm test
